# Generated by Django 5.0.6 on 2024-10-20 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitestapp', '0001_initial'),
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fileinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('function', models.CharField(max_length=300)),
                ('prd_name', models.CharField(max_length=30)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='aitestapp/data')),
            ],
        ),
        migrations.CreateModel(
            name='interface_fileinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=300)),
                ('prd_name', models.CharField(max_length=300, null=True)),
                ('path', models.FileField(upload_to='aitestapp/interface_file')),
                ('remark', models.CharField(max_length=3000, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_id', models.CharField(max_length=20)),
                ('loginfo', models.CharField(max_length=6000)),
                ('vedio_path', models.CharField(max_length=300)),
                ('picture_path', models.CharField(max_length=300)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('execute_count', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='project_config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=40)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('needs', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='vectors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vector_id', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='interface_data_config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_desc', models.CharField(max_length=200)),
                ('data_info', models.CharField(max_length=600, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('interface_api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitestapp.interface_fileinfo', verbose_name='interface_api_id')),
            ],
        ),
        migrations.CreateModel(
            name='interface_apiinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('example', models.CharField(max_length=300)),
                ('response', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=300, null=True)),
                ('params', models.CharField(max_length=600)),
                ('status', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=30)),
                ('interface_apiinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitestapp.interface_fileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='interface_testcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('api_name', models.CharField(max_length=300)),
                ('testpoint', models.CharField(max_length=300)),
                ('expectedresult', models.CharField(max_length=300)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('testcaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitestapp.interface_fileinfo', verbose_name='testcaseid')),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('testcase', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=30, null=True)),
                ('operation', models.CharField(max_length=300)),
                ('expectedresult', models.CharField(max_length=300)),
                ('actual_results', models.CharField(blank=True, max_length=300, null=True)),
                ('execution_time', models.DateField(auto_now_add=True)),
                ('execution_person', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('testcaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitestapp.fileinfo', verbose_name='testcaseid')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session', verbose_name='会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
