# Generated by Django 5.0.6 on 2024-10-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitestapp', '0002_fileinfo_interface_fileinfo_log_project_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_data_config',
            name='interface_api_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitestapp.interface_fileinfo'),
        ),
    ]
