# Generated by Django 5.0.6 on 2024-11-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitestapp', '0008_remove_testcase_result_execute_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testreport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.CharField(max_length=20)),
                ('successes', models.CharField(max_length=20)),
                ('failures', models.CharField(max_length=20)),
                ('errors', models.CharField(max_length=20)),
                ('skipped', models.CharField(max_length=20)),
                ('expectedFailures', models.CharField(max_length=20)),
                ('unexpectedSuccesses', models.CharField(max_length=20)),
                ('execute_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
